# Generated by Django 5.2.5 on 2025-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
